steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/paperboy-lightweight', '.']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/paperboy-lightweight']

  # Deploy to Cloud Run with settings from deploy_cloudrun.sh
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'paperboy'
      - '--image=gcr.io/$PROJECT_ID/paperboy-lightweight'
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=50'
      - '--concurrency=1'
      - '--timeout=3600'
      - '--no-allow-unauthenticated'
      - '--set-env-vars=USE_LIGHTWEIGHT=true,PORT=8080'
      - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,API_KEY=API_KEY:latest,LOGFIRE_TOKEN=LOGFIRE_TOKEN:latest'

# Optional: Configure timeout for the build
timeout: '1200s'

# Optional: Specify machine type for faster builds
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY