services:
  api:
    image: paperboy:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paperboy-api
    ports:
      - "127.0.0.1:8000:8080" # Map local 8000 to container 8080
    env_file:
      - ./config/.env
    environment:
      - PORT=8080
      - USE_LIGHTWEIGHT=true # Ensure lightweight mode
      - SHUTDOWN_TIMEOUT=30
      - CACHE_TTL=3600
      - LOG_LEVEL=INFO # Changed from WARNING to INFO for better debugging
      - UVICORN_ACCESS_LOG=1 # Enable access logs for debugging
      - UVICORN_LOG_LEVEL=info
      - TASK_TIMEOUT=600 # 10 minutes for digest generation
      - REQUEST_TIMEOUT=595 # Just under 10 minutes for HTTP requests
      - HTTP_TIMEOUT=60 # 1 minute for general HTTP operations
    volumes:
      - ./config/.env:/app/config/.env:ro # Mount .env file as read-only
      - ./data:/app/data # Mount data directory for state persistence
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation
    cap_drop:
      - ALL # Drop all capabilities
    cap_add:
      - NET_BIND_SERVICE # Only add capability needed for port binding
    read_only: true # Make container filesystem read-only
    tmpfs:
      - /tmp # Temporary storage for runtime
      - /run
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 12h
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "4m"
    deploy:
      resources:
        limits:
          cpus: "1.0" # Increased for enhanced features
          memory: 1G # Increased for enhanced features
        reservations:
          cpus: "0.2"
          memory: 512M
