version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./config/.env
    environment:
      - ENVIRONMENT=development
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload  # Added --reload for development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/digest-status/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 