version: '3.8'

services:
  api:
    image: paperboy:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paperboy-api
    ports:
      - "127.0.0.1:8000:8080"  # Map local 8000 to container 8080
    env_file:
      - ./config/.env
    environment:
      - PORT=8080
      - USE_LIGHTWEIGHT=true  # Ensure lightweight mode
      - LOG_LEVEL=WARNING
      - UVICORN_ACCESS_LOG=0
      - UVICORN_LOG_LEVEL=warning
    volumes:
      - ./config/.env:/app/config/.env:ro  # Mount .env file as read-only
      - ./data:/app/data  # Mount data directory for state persistence
    security_opt:
      - no-new-privileges:true  # Prevent privilege escalation
    cap_drop:
      - ALL  # Drop all capabilities
    cap_add:
      - NET_BIND_SERVICE  # Only add capability needed for port binding
    read_only: true  # Make container filesystem read-only
    tmpfs:
      - /tmp  # Temporary storage for runtime
      - /run
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/digest-status/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "4m"
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Reduced for lightweight
          memory: 512M  # Reduced for lightweight
        reservations:
          cpus: '0.1'
          memory: 256M